<?php

namespace Container6cynvmL;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KXqYL38Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kXqYL38' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kXqYL38'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManagerInterface' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'securityAuthenticator' => ['privates', 'App\\Security\\SecurityAuthenticator', 'getSecurityAuthenticatorService', true],
            'userAuthenticatorInterface' => ['privates', 'security.user_authenticator', 'getSecurity_UserAuthenticatorService', true],
            'userPasswordHasherInterface' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'entityManagerInterface' => '?',
            'securityAuthenticator' => 'App\\Security\\SecurityAuthenticator',
            'userAuthenticatorInterface' => '?',
            'userPasswordHasherInterface' => '?',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
