<?php

namespace ContainerN0rxKTb;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JPEmy_IService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jPEmy.I' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jPEmy.I'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'availabilityRepository' => ['privates', 'App\\Repository\\AvailabilityRepository', 'getAvailabilityRepositoryService', true],
            'entityManagerInterface' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'availabilityRepository' => 'App\\Repository\\AvailabilityRepository',
            'entityManagerInterface' => '?',
        ]);
    }
}
