<?php

namespace ContainerJiOEx0Q;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_57UVbl1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.57UVbl1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.57UVbl1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManagerInterface' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'user' => ['privates', '.errored..service_locator.57UVbl1.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.57UVbl1": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'entityManagerInterface' => '?',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
