<?php

namespace ContainerJiOEx0Q;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OeNY5oGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oeNY5oG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oeNY5oG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cpsCardOwnerRepository' => ['privates', 'App\\Repository\\CpsCardOwnerRepository', 'getCpsCardOwnerRepositoryService', true],
            'entityManagerInterface' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'userPasswordHasherInterface' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'cpsCardOwnerRepository' => 'App\\Repository\\CpsCardOwnerRepository',
            'entityManagerInterface' => '?',
            'userPasswordHasherInterface' => '?',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
