<?php

namespace ContainerC7EYX7S;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Frza3KnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.frza3Kn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.frza3Kn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManagerInterface' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'user' => ['privates', '.errored..service_locator.frza3Kn.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.frza3Kn": it references class "App\\Entity\\User" but no such service exists.'],
            'userPasswordHasherInterface' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
        ], [
            'entityManagerInterface' => '?',
            'user' => 'App\\Entity\\User',
            'userPasswordHasherInterface' => '?',
        ]);
    }
}
