<?php

namespace ContainerC7EYX7S;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WhLgZI0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WhLgZI0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WhLgZI0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'availabilityRepository' => ['privates', 'App\\Repository\\AvailabilityRepository', 'getAvailabilityRepositoryService', true],
            'surgeryNotificationRepository' => ['privates', 'App\\Repository\\SurgeryNotificationRepository', 'getSurgeryNotificationRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'availabilityRepository' => 'App\\Repository\\AvailabilityRepository',
            'surgeryNotificationRepository' => 'App\\Repository\\SurgeryNotificationRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
