<?php

namespace ContainerC7EYX7S;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_On5_8BRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.on5.8BR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.on5.8BR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'availability' => ['privates', '.errored..service_locator.on5.8BR.App\\Entity\\Availability', NULL, 'Cannot autowire service ".service_locator.on5.8BR": it references class "App\\Entity\\Availability" but no such service exists.'],
            'availabilityRepository' => ['privates', 'App\\Repository\\AvailabilityRepository', 'getAvailabilityRepositoryService', true],
            'entityManagerInterface' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'availability' => 'App\\Entity\\Availability',
            'availabilityRepository' => 'App\\Repository\\AvailabilityRepository',
            'entityManagerInterface' => '?',
        ]);
    }
}
