<?php

namespace ContainerC7EYX7S;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAvailabilityService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.on5.8BR.App\Entity\Availability' shared service.
     *
     * @return \App\Entity\Availability
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.on5.8BR": it references class "App\\Entity\\Availability" but no such service exists.');
    }
}
